spring:
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          # https://platform.openai.com/docs/models/gpt-4o
          model: "gpt-4o-mini" # cheapest model for now
      embedding:
        options:
          # https://platform.openai.com/docs/guides/embeddings/what-are-embeddings
          model: "text-embedding-3-small" # cheapest model for now