initialize: false

spring:
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          # https://platform.openai.com/docs/models/gpt-4o
          model: "gpt-4o-mini" # cheapest model for now
      embedding:
        options:
          # https://platform.openai.com/docs/guides/embeddings/what-are-embeddings
          model: "text-embedding-3-small" # cheapest model for now
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        initialize-schema: true # Die notwendige Collection mit der korrekten Dimension für die Emebddings wird automatisch erstellt
        databaseName: "default"
        collectionName: "default"
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE